In [1]:
import numpy as np

In [2]:
mylist = [i for i in range(10)]
type(mylist)

list

In [3]:
mylist*2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

this happened because mylist is a list, not an array

In [5]:
myarra = np.array(mylist)
type(myarra)

numpy.ndarray

In [6]:
myarra*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
myarra**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [8]:
myarra**0.5

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [10]:
mymatrix = np.array([[0,1,5],[-2,1,4],[7,8,9]])
mymatrix

array([[ 0,  1,  5],
       [-2,  1,  4],
       [ 7,  8,  9]])

In [11]:
mymatrix[:,0:1]

array([[ 0],
       [-2],
       [ 7]])

In [13]:
mymatrix[0:2,2:3]

array([[5],
       [4]])

In [12]:
mymatrix[0:3,1:2]

array([[1],
       [1],
       [8]])

# arange

In [14]:
myarange = np.arange(10)
myarange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
myrangestep = np.arange(0,10,2)
myrangestep

array([0, 2, 4, 6, 8])

# zeros and ones

generate arrays of zeros or ones

In [18]:
Z = np.zeros(4)
Z

array([0., 0., 0., 0.])

In [20]:
Z3 = np.zeros((3,3))
Z3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
O1 = np.ones(5)
O1

array([1., 1., 1., 1., 1.])

In [24]:
O6 = np.ones((6,6))
O6

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

# linspace

return evenly spaced numbers over a specified interval

In [28]:
L = np.linspace(0,25,25)
L

array([ 0.        ,  1.04166667,  2.08333333,  3.125     ,  4.16666667,
        5.20833333,  6.25      ,  7.29166667,  8.33333333,  9.375     ,
       10.41666667, 11.45833333, 12.5       , 13.54166667, 14.58333333,
       15.625     , 16.66666667, 17.70833333, 18.75      , 19.79166667,
       20.83333333, 21.875     , 22.91666667, 23.95833333, 25.        ])

the third number in the bracket is how many numbers you want, the first 2 are the interval.

In [36]:
L = np.linspace(1,25,9)
L

array([ 1.,  4.,  7., 10., 13., 16., 19., 22., 25.])

In [37]:
L3 = L.reshape(3,3)
L3

array([[ 1.,  4.,  7.],
       [10., 13., 16.],
       [19., 22., 25.]])

# eye

creates an identity matrix

In [38]:
I2 = np.eye(2)
I2

array([[1., 0.],
       [0., 1.]])

In [39]:
I4 = np.eye(4)
I4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [41]:
I43 = np.eye(4,3)
I43

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [42]:
I43[0:2,0:2]

array([[1., 0.],
       [0., 1.]])

# Random

Numpy has lots of ways to create random number arrays

## rand
create an array of the given shape and populate it with random samples from a uniform distribution over [o,1]
in (a,b) a is row(horizontal), b is columns(vertical)

In [45]:
import random

In [47]:
arr = np.random.rand(3,4)
arr

array([[0.32876837, 0.61127328, 0.1037141 , 0.70277267],
       [0.61809401, 0.64388793, 0.5283617 , 0.96649201],
       [0.97702754, 0.61217544, 0.90532362, 0.05180614]])

In [49]:
from numpy.random import rand

In [51]:
arr_simple = rand(3,4)
arr_simple

array([[0.71840089, 0.11446555, 0.76030412, 0.37830551],
       [0.3939841 , 0.7864034 , 0.22665343, 0.46487585],
       [0.28176343, 0.22193913, 0.26284904, 0.083644  ]])

## randn
return a sample or samples from the "standard normal" distribution unlike rand which is uniform:

In [52]:
from numpy.random import randn

In [53]:
mat = randn(3,2)
mat

array([[ 1.12991599,  1.03046883],
       [ 1.62595062, -0.97466067],
       [-0.1103321 , -1.09928538]])

In [54]:
l = lambda x: x.split('@')

In [55]:
l('seun@howard.edu')

['seun', 'howard.edu']

In [56]:
l = lambda x: x.split('@')[0]

In [57]:
l('seun@howard.edu')

'seun'

In [58]:
l = lambda x: x.split('@')[1]

In [59]:
l('seun@howard.edu')

'howard.edu'

In [61]:
seq = [i for i in range (7)]
seq

[0, 1, 2, 3, 4, 5, 6]